env:
  MAJOR_VERSION: 3.3
jobs:
  Linux:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Checkout submodules
      run: 'git submodule sync --recursive

        git submodule update --init --force --recursive --depth=1

        '
      shell: bash
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: liberica
        java-package: jdk+fx
        java-version: 17.0.9
    - continue-on-error: true
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - continue-on-error: true
      name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - continue-on-error: true
      name: Build minor update
      run: 'build-bin/package-update.sh

        '
name: Build Minor Update
on:
  repository_dispatch:
    types: trigger-ga___build-update-minor.yml
