jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Checkout submodules
      run: 'git submodule sync --recursive

        git submodule update --init --force --recursive --depth=1

        '
      shell: bash
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: liberica
        java-package: jdk+fx
        java-version: 17.0.9
    - continue-on-error: true
      name: Build GanttProject
      run: ./gradlew --no-daemon build
    - continue-on-error: true
      name: Publish libs
      run: ./gradlew --no-daemon publishToMavenLocal
    - continue-on-error: true
      name: Build Colloboque
      run: cd cloud.ganttproject.colloboque && ./gradlew --no-daemon build
name: Build and Test
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
